### ISSUE TITLE
Panic on parsing mpd response

### ISSUE THREAD

**Issue by xa888s** [jkristell/async-mpd#5]
I am currently writing a music client with this library, and it is really nice to use, thanks! I am running into an issue that whenever a specific song starts playing, it crashes. All other songs seem to work fine. The song is Promiscuous by Nelly Furtado.
Tags:
- Filename: `03 - Promiscuous (Feat. Timbaland).flac`
- Genre: `Pop`
- Track: `03`
- Date: `2006`
- Album: `Loose`
- Artist: `Nelly Furtado`
- Title `Promiscuous (Feat. Timbaland)`
Stack trace:
```
thread 'main' panicked at 'Failed to parse mpd response: “” with EOF while parsing a value', /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:342
  13: async_mpd::client::MpdClient::status::{{closure}}::{{closure}}
             at /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/macros.rs:16
  14: core::result::Result<T,E>::unwrap_or_else
             at /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/result.rs:853
  15: async_mpd::client::MpdClient::status::{{closure}}
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-mpd-0.2.1/src/client.rs:57
  16: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:73
  17: rmpc::App::run::{{closure}}
             at src/main.rs:161
  18: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:73
  19: rmpc::main::main::{{closure}}
             at src/main.rs:196
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:73
  21: rmpc::main::{{closure}}
             at src/main.rs:193
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/future/mod.rs:73
  23: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll::{{closure}}
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/builder.rs:198
  24: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/task_locals_wrapper.rs:60
  25: std::thread::local::LocalKey<T>::try_with
             at /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  26: std::thread::local::LocalKey<T>::with
             at /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  27: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/task_locals_wrapper.rs:55
  28: <async_std::task::builder::SupportTaskLocals<F> as core::future::future::Future>::poll
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/builder.rs:196
  29: async_executor::LocalExecutor::run::{{closure}}
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-0.1.2/src/lib.rs:339
  30: scoped_tls::ScopedKey<T>::set
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
  31: async_executor::LocalExecutor::run
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-0.1.2/src/lib.rs:337
  32: async_std::task::executor::run::{{closure}}::{{closure}}::{{closure}}
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/executor.rs:31
  33: scoped_tls::ScopedKey<T>::set
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137
  34: async_executor::Executor::enter
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-executor-0.1.2/src/lib.rs:151
  35: async_std::task::executor::run::{{closure}}::{{closure}}
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/executor.rs:31
  36: async_std::task::executor::enter
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/executor.rs:44
  37: async_std::task::executor::run::{{closure}}
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/executor.rs:31
  38: std::thread::local::LocalKey<T>::try_with
             at /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  39: std::thread::local::LocalKey<T>::with
             at /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  40: async_std::task::executor::run
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/executor.rs:31
  41: async_std::task::builder::Builder::blocking::{{closure}}::{{closure}}
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/builder.rs:170
  42: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current::{{closure}}
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/task_locals_wrapper.rs:60
  43: std::thread::local::LocalKey<T>::try_with
             at /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  44: std::thread::local::LocalKey<T>::with
             at /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  45: async_std::task::task_locals_wrapper::TaskLocalsWrapper::set_current
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/task_locals_wrapper.rs:55
  46: async_std::task::builder::Builder::blocking::{{closure}}
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/builder.rs:167
  47: std::thread::local::LocalKey<T>::try_with
             at /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:263
  48: std::thread::local::LocalKey<T>::with
             at /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/thread/local.rs:239
  49: async_std::task::builder::Builder::blocking
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/builder.rs:160
  50: async_std::task::block_on::block_on
             at /home/abyss/.cargo/registry/src/github.com-1ecc6299db9ec823/async-std-1.6.3/src/task/block_on.rs:33
  51: rmpc::main
             at src/main.rs:193
  52: std::rt::lang_start::{{closure}}
             at /home/abyss/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  53: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  54: std::panicking::try::do_call
             at src/libstd/panicking.rs:297
  55: std::panicking::try
             at src/libstd/panicking.rs:274
  56: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  57: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  58: main
  59: __libc_start_main
  60: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by xa888s** [comment]
I have isolated it to lines 51 and 58 in `client.rs`

**Comment by xa888s** [comment]
Adding a debug reveals empty string (just realized it already prints it :P)
```
[/home/abyss/projects/async-mpd/src/client.rs:57] &lines = "volume: 50\nrepeat: 1\nrandom: 0\nsingle: 0\nconsume: 0\nplaylist: 2\nplaylistlength: 3\nmixrampdb: 0.000000\nstate: play\nxfade: 5\nsong: 1\nsongid: 2\ntime: 0:242\nelapsed: 0.000\nbitrate: 332\nduration: 242.293\naudio: 44100:16:2\nnextsong: 2\nnextsongid: 3"
[/home/abyss/projects/async-mpd/src/client.rs:57] &lines = "volume: 50\nrepeat: 1\nrandom: 0\nsingle: 0\nconsume: 0\nplaylist: 2\nplaylistlength: 3\nmixrampdb: 0.000000\nstate: play\nxfade: 5\nsong: 2\nsongid: 3\ntime: 0:64\nelapsed: 0.000\nbitrate: 0\nduration: 64.080\naudio: 44100:16:2\nnextsong: 0\nnextsongid: 1"
[/home/abyss/projects/async-mpd/src/client.rs:57] &lines = ""
```

**Comment by jkristell** [comment]
Hi and thanks for the response!

It could be that the server closed the connection? The EOF error seems to indicate that. The mpd server is really eager to disconnect if you don't put the connection in idle state or continuously send it some command. I use to have some code in cmd that checked the connection and reconnected if the server had closed the connection, but it was a bit of a hack so I removed it. 

So your options right now is either to put the server in Idle state between commands or open a new connection for each command.

I'm not really sure how to solve this. Ideas are very welcome!

**Comment by xa888s** [comment]
I was thinking you could get a new connection in the `.unwrap_or_else()` and re run the command? I think you could also return a new error type to show the user something so they can reset their own connection? Maybe like a `Result<Status, MpdError>` with one of the variants being `Disconnected`. Then the user can choose what to do if needed. I think it is fine to provide an error but a panic is very drastic for something that seems like it could happen often? If a panic is required than a section in the docs that warns about this would be important to inform the user of their duties. Can't really think of any better solutions right now but let me know what you think.

**Comment by jkristell** [comment]
The Result<_, MpdError> make sense. Then the user of the library can handle this the way feel is right and don't have to do the Idle NoIdle dance.

Yeah, to panic is really bad, fully agree with you. I can probably implement this during the week or if you want to do feel free to send a pull request! :-)

**Comment by jkristell** [comment]
Been reading up on error handling library, will implement this tonight!

**Comment by jkristell** [comment]
Implemented this and added a new example on how to use it.

But I'm leaning on moving the reconnect step back into the library again to make the library nicer to use.
